import { join } from "node:path";
import type { ConfidenceLevel } from "../domain/work-event.js";
import type { DigestClaimItem, WeeklyDigestView } from "./digest.js";
import { slugify } from "./markdown-writer.js";

const CONFIDENCE_LABEL: Record<ConfidenceLevel, string> = {
  high: "alta",
  medium: "media",
  low: "baja",
};

/** Ruta del digest semanal: `<documentsPath>/digests/{repo}-{semana}.md`. */
export function buildDigestPath(
  documentsPath: string,
  repository: string,
  weekLabel: string,
): string {
  const repoSlug = slugify(repository);
  return join(documentsPath, "digests", `${repoSlug}-${weekLabel}.md`);
}

function renderClaimList(items: DigestClaimItem[], language: "es" | "en" = "es"): string[] {
  if (items.length === 0) {
    return [language === "en" ? "_No items in this window._" : "_Sin ítems en esta ventana._"];
  }
  return items.map((item) => `- ${item.text} ([${item.label}](${item.url}))`);
}

/**
 * Renderiza el digest semanal como Markdown trazable: banner de confianza,
 * overview, secciones qué se hizo / decisiones / pendientes, drift y el índice
 * de eventos de la ventana con su link.
 */
export function renderWeeklyDigest(
  view: WeeklyDigestView,
  language: "es" | "en" = "es"
): string {
  const isEn = language === "en";
  const levelLabel = isEn ? view.confidence.level : CONFIDENCE_LABEL[view.confidence.level];
  const lines: string[] = [
    isEn 
      ? `# Weekly Digest — ${view.repository} (${view.weekLabel})`
      : `# Digest semanal — ${view.repository} (${view.weekLabel})`,
    "",
    isEn
      ? "> Digest view generated by Mico 🐒 aggregating work events for this window."
      : "> Vista de digest generada por Mico 🐒 agregando los eventos de trabajo (WorkEvent) de la ventana.",
    "",
  ];

  if (view.needsHumanReview) {
    lines.push(
      isEn
        ? `> ⚠️ **Human review recommended** — aggregate confidence is ${levelLabel} (score ${view.confidence.score}). The digest contains low-confidence events; verify before assuming correctness.`
        : `> ⚠️ **Revisión humana recomendada** — la confianza agregada es ${levelLabel} (score ${view.confidence.score}). El digest contiene eventos de baja confianza; verificá antes de darlo por cierto.`,
      "",
    );
  }

  lines.push(
    isEn ? "| Field | Value |" : "| Campo | Valor |",
    "| --- | --- |",
    isEn ? `| Repository | \`${view.repository}\` |` : `| Repositorio | \`${view.repository}\` |`,
    isEn ? `| Window | ${view.from} → ${view.to} |` : `| Ventana | ${view.from} → ${view.to} |`,
    isEn ? `| Week | ${view.weekLabel} |` : `| Semana | ${view.weekLabel} |`,
    isEn ? `| Events | ${view.eventCount} |` : `| Eventos | ${view.eventCount} |`,
    isEn ? `| Aggregate confidence | ${levelLabel} (score ${view.confidence.score}) |` : `| Confianza agregada | ${levelLabel} (score ${view.confidence.score}) |`,
    isEn ? `| Human review | ${view.needsHumanReview ? "Yes" : "No"} |` : `| Revisión humana | ${view.needsHumanReview ? "Sí" : "No"} |`,
    isEn ? `| Generated | ${new Date().toISOString()} |` : `| Generado | ${new Date().toISOString()} |`,
    "",
    "---",
    "",
    isEn ? "## Overview" : "## Resumen",
    "",
    view.overview.trim(),
    "",
    isEn ? "## What was done" : "## Qué se hizo",
    "",
    ...renderClaimList(view.did, language),
    "",
    isEn ? "## Decisions" : "## Decisiones",
    "",
    ...renderClaimList(view.decisions, language),
    "",
    isEn ? "## Pending / Next Steps" : "## Pendientes / por avanzar",
    "",
    ...renderClaimList(view.pending, language),
    "",
    isEn ? "## Drift / Gaps" : "## Drift / huecos",
    "",
  );

  if (view.drift.length === 0) {
    lines.push(isEn ? "_No drift signals detected in this window._" : "_No se detectaron señales de drift en esta ventana._");
  } else {
    for (const signal of view.drift) {
      lines.push(`- ${signal.reason} — [${signal.title}](${signal.url})`);
    }
  }

  lines.push("", isEn ? "## Window Events" : "## Eventos de la ventana", "");
  if (view.events.length === 0) {
    lines.push(isEn ? "_No events recorded in this window._" : "_No hay eventos registrados en la ventana._");
  } else {
    for (const stored of view.events) {
      const level = isEn ? stored.confidence.level : CONFIDENCE_LABEL[stored.confidence.level];
      lines.push(
        `- [${stored.workEvent.title}](${stored.workEvent.url}) — ${stored.workEvent.occurredAt} (${isEn ? "confidence" : "confianza"} ${level})`,
      );
    }
  }

  lines.push(
    "",
    "## Confianza",
    "",
    `- Nivel agregado: ${levelLabel} (score ${view.confidence.score})`,
    `- Revisión humana: ${view.needsHumanReview ? "Sí" : "No"}`,
    "- Motivos:",
  );
  for (const reason of view.confidence.reasons) {
    lines.push(`  - ${reason}`);
  }

  return `${lines.join("\n")}\n`;
}
